package me.okonecny.markdowneditor.internal.interactive

import androidx.compose.ui.layout.LayoutCoordinates
import androidx.compose.ui.text.TextRange

/**
 * Class representing an interactive GUI element.
 * Best created in onGloballyPositioned modifier.
 * @param id An id generated by InteractiveScope.rememberInteractiveId()
 * @param layoutCoordinates Global layout coordinates used to sort the interactive components for the purpose of prev/next navigation.
 */
data class Interactive(
    val id: InteractiveId,
    val layoutCoordinates: LayoutCoordinates,
    val textRange: TextRange
)